# Generated by Django 3.2.7 on 2021-11-01 00:03

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('ticker', models.CharField(max_length=10, unique=True)),
                ('vol1', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('vol2', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('total_vol', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('accum', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('highlighted', models.TextField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
