# Generated by Django 3.2.7 on 2021-10-31 12:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('ticker', models.CharField(max_length=10)),
                ('vol1', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('vol2', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('accum', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
