# Generated by Django 3.2.7 on 2021-10-31 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticker',
            name='ticker',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
