# Generated by Django 3.2.7 on 2021-11-03 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickers', '0002_remove_ticker_highlighted'),
    ]

    operations = [
        migrations.CreateModel(
            name='dividend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('ex_date', models.DateField()),
                ('pay_date', models.DateField()),
                ('div_val', models.DecimalField(decimal_places=6, max_digits=8)),
                ('div_rat', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
    ]
