# Generated by Django 3.2.7 on 2021-11-03 13:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickers', '0003_dividend'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dividend',
            options={'ordering': ['created']},
        ),
        migrations.AddField(
            model_name='dividend',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='dividends', to='auth.user'),
            preserve_default=False,
        ),
    ]
