# Generated by Django 3.2.7 on 2021-11-03 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickers', '0004_auto_20211103_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='dividend',
            name='ticker',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, to='tickers.ticker'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ticker',
            name='ticker',
            field=models.CharField(default='someerror', max_length=10, unique=True),
        ),
    ]
