# Generated by Django 3.2.7 on 2021-11-03 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickers', '0005_auto_20211103_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dividend',
            name='ticker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tickers.ticker', to_field='ticker'),
        ),
    ]
