# Generated by Django 3.2.7 on 2021-11-07 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickers', '0006_alter_dividend_ticker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticker',
            name='ticker',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
