# Generated by Django 3.2.7 on 2021-11-07 08:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickers', '0007_alter_ticker_ticker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dividend',
            name='div_rat',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='dividend',
            name='pay_date',
            field=models.DateField(blank=True, default='2020/1/1', null=True),
        ),
        migrations.AlterField(
            model_name='ticker',
            name='accum',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='ticker',
            name='total_vol',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='ticker',
            name='vol1',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='ticker',
            name='vol2',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
